services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      # - /app/node_modules
    depends_on:
      - db
  db:
    build: 
      context: "."
      dockerfile: "db.Dockerfile"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedule_arranger
    ports:
      - "5432:5432"
    volumes:
      - schedule-arranger-data:/var/lib/postgresql/data

volumes:
  schedule-arranger-data:

